- name: include plan vars
  include_vars:
    file: "{{ _apb_plan_id }}.yml"
- name: generate b62 hash
  shell: "16to62 {{ params_hash }}"
  register: command_output
- name: set fact
  set_fact:
    stack_suffix: "{{ command_output.stdout }}"
- name: Remove SNS topic
  cloudformation:
    stack_name: "apb-sns-{{ stack_suffix }}"
    state: "absent"
    region: "{{ region }}"
  register: sns
- name: Ensure CloudFormation stack deletion was successful
  debug:
    var: sns.log
- name: Remove IAM user
  iam:
    iam_type: user
    name: "apb-sns-iam-{{ stack_suffix }}"
    state: absent
  when: _apb_plan_id != "subscription"
- name: Remove IAM policy
  iam_policy:
    iam_type: user
    iam_name: "apb-sns-iam-{{ stack_suffix }}"
    policy_name: "SNS-APB-{{ stack_suffix }}"
    state: absent
  when: _apb_plan_id != "subscription"
