apiVersion: v1
kind: Template
metadata:
  name: sns
parameters:
  - name: namespace
  - name: service_class_name
  - name: stack_identifier
  - name: aws_access_key
  - name: aws_secret_key
  - name: aws_region
objects:
  - apiVersion: servicecatalog.k8s.io/v1alpha1
    kind: Instance
    metadata:
      name: sns
      namespace: ${namespace}
    spec:
      serviceClassName: ${service_class_name}
      planName: default
      parameters:
        stack_identifier: ${stack_identifier}
        aws_access_key: ${aws_access_key}
        aws_secret_key: ${aws_secret_key}
        region: ${aws_region}
        SubscriptionEndPoint: "+11111111111"
        SubscriptionProtocol: "sms"
