AWSTemplateFormatVersion: 2010-09-09
Description: Best Practice SNS Topic
Parameters:
  SubscriptionEndPoint:
    Type: String
    Description: >-
      The endpoint that receives notifications from the Amazon SNS topic.
      If left blank no subscription will be added to the topic.
      The endpoint value depends on the protocol that you specify. This could be a
      URL, ARN or SMS-capable telephone number.
    Default: ""
  SubscriptionProtocol:
    Type: String
    Description: >-
      The subscription's protocol.
      Examples: "http", "https", "email", "email-json", "sms", "sqs", "application", "lambda".
    Default: ""
    AllowedValues:
      - ""
      - http
      - https
      - email
      - email-json
      - sms
      - sqs
      - application
      - lambda
    Default: sqs
  CreateTopic:
    Type: String
    Description: >-
      Should we create a topic or not ?
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  ExistingTopicArn:
    Type: String
    Description: >-
      If not creating a topic, define the arn for an existing topic
    Default: ""
Conditions:
  AddSub: !Not
    - !Equals
      - !Ref SubscriptionEndPoint
      - ''
  AddTopic: !Equals
    - !Ref CreateTopic
    - 'Yes'
Resources:
  SNSTopic:
    Condition: AddTopic
    Type: 'AWS::SNS::Topic'
  SNSSubscription:
    Condition: AddSub
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Ref SubscriptionEndPoint
      Protocol: !Ref SubscriptionProtocol
      TopicArn: !If
        - AddTopic
        - !Ref SNSTopic
        - !Ref ExistingTopicArn
Outputs:
  TopicARN:
    Description: ARN of SNS Topic
    Value: !If
      - AddTopic
      - !Ref SNSTopic
      - !Ref ExistingTopicArn